server:
  port: 8889
spring:
  application:
    name: store
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/store?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8
        username: root
        password:
        initialSize: 20
        minIdle: 5
        maxActive: 200
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        dbcp:
          remove-abandoned: true
          remove-abandoned-timeout: 180
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
management:
  endpoints:
    web:
      exposure:
        include: 'info,health'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
      sensitive: false
    restart:
      enabled: true

mybatis-plus:
  mapperLocations: mybatis/**Mapper.xml
  type-aliases-package: com.boot.store.entity
  global-config:
    db-config:
      id-type: INPUT
      field-strategy: NOT_EMPTY
      column-underline: true
      #capital-mode: true
    refresh: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false